//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJ.Code.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AJ.Code.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Philippines과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _Sint_Maarten__Dutch_part_ {
            get {
                return ResourceManager.GetString("@Sint Maarten (Dutch part)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Andorra과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   United Arab Emirates과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AE {
            get {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Afghanistan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Africa과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AFRICA {
            get {
                return ResourceManager.GetString("AFRICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antigua and Barbuda과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anguilla과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AI {
            get {
                return ResourceManager.GetString("AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Albania과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Armenia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antarctica과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ANTARCTICA {
            get {
                return ResourceManager.GetString("ANTARCTICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Angola과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AO {
            get {
                return ResourceManager.GetString("AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antarctica과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AQ {
            get {
                return ResourceManager.GetString("AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argentina과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   American Samoa과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Asia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ASIA {
            get {
                return ResourceManager.GetString("ASIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Austria과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Australia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aruba과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AW {
            get {
                return ResourceManager.GetString("AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Åland Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AX {
            get {
                return ResourceManager.GetString("AX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Azerbaijan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bosnia and Herzegovina과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Barbados과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BB {
            get {
                return ResourceManager.GetString("BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bangladesh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belgium과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Burkina Faso과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BF {
            get {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulgaria과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bahrain과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH {
            get {
                return ResourceManager.GetString("BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Burundi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BI {
            get {
                return ResourceManager.GetString("BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Benin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BJ {
            get {
                return ResourceManager.GetString("BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saint Barthélemy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BL {
            get {
                return ResourceManager.GetString("BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bermuda과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brunei Darussalam과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bolivia, Plurinational State of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bonaire, Sint Eustatius and Saba과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BQ {
            get {
                return ResourceManager.GetString("BQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brazil과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bahamas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bhutan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bouvet Island과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BV {
            get {
                return ResourceManager.GetString("BV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Botswana과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belarus과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belize과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canada과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cocos (Keeling) Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Congo, the Democratic Republic of the과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CD {
            get {
                return ResourceManager.GetString("CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Central African Republic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CF {
            get {
                return ResourceManager.GetString("CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Congo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CG {
            get {
                return ResourceManager.GetString("CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switzerland과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Côte d&apos;Ivoire과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cook Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CK {
            get {
                return ResourceManager.GetString("CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cameroon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   China과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colombia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Costa Rica과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cuba과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CU {
            get {
                return ResourceManager.GetString("CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cabo Verde과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Curaçao과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CW {
            get {
                return ResourceManager.GetString("CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Christmas Island과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CX {
            get {
                return ResourceManager.GetString("CX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyprus과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CY {
            get {
                return ResourceManager.GetString("CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Czechia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Germany과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Djibouti과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DJ {
            get {
                return ResourceManager.GetString("DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Denmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dominica과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dominican Republic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algeria과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ecuador과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Estonia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Egypt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Western Sahara과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EH {
            get {
                return ResourceManager.GetString("EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eritrea과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ER {
            get {
                return ResourceManager.GetString("ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spain과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ethiopia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Europe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EUROPE {
            get {
                return ResourceManager.GetString("EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finland과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiji과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FJ {
            get {
                return ResourceManager.GetString("FJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Falkland Islands (Malvinas)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FK {
            get {
                return ResourceManager.GetString("FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Micronesia, Federated States of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faroe Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FO {
            get {
                return ResourceManager.GetString("FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   France과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gabon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   United Kingdom of Great Britain and Northern Ireland과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grenada과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GD {
            get {
                return ResourceManager.GetString("GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guam과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   French Guiana과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GF {
            get {
                return ResourceManager.GetString("GF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guernsey과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GG {
            get {
                return ResourceManager.GetString("GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ghana과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GH {
            get {
                return ResourceManager.GetString("GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gibraltar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greenland과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gambia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GM {
            get {
                return ResourceManager.GetString("GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guinea과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GN {
            get {
                return ResourceManager.GetString("GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guadeloupe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GP {
            get {
                return ResourceManager.GetString("GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equatorial Guinea과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GQ {
            get {
                return ResourceManager.GetString("GQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greece과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   South Georgia and the South Sandwich Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guatemala과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GT {
            get {
                return ResourceManager.GetString("GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guam과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GU {
            get {
                return ResourceManager.GetString("GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guinea-Bissau과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GW {
            get {
                return ResourceManager.GetString("GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guyana과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GY {
            get {
                return ResourceManager.GetString("GY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hong Kong과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HK {
            get {
                return ResourceManager.GetString("HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heard Island and McDonald Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HM {
            get {
                return ResourceManager.GetString("HM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Honduras과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Croatia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Haiti과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hungary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indonesia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ireland과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Israel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Isle of Ma과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IM {
            get {
                return ResourceManager.GetString("IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   India과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   British Indian Ocean Territory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iraq과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iran, Islamic Republic of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iceland과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jersey과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JE {
            get {
                return ResourceManager.GetString("JE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jamaica과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JM {
            get {
                return ResourceManager.GetString("JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jordan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JO {
            get {
                return ResourceManager.GetString("JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JP {
            get {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kenya과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KE {
            get {
                return ResourceManager.GetString("KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kyrgyzstan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KG {
            get {
                return ResourceManager.GetString("KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cambodia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KH {
            get {
                return ResourceManager.GetString("KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kiribati과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KI {
            get {
                return ResourceManager.GetString("KI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comoros과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saint Kitts and Nevis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KN {
            get {
                return ResourceManager.GetString("KN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korea, Democratic People&apos;s Republic of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KP {
            get {
                return ResourceManager.GetString("KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korea, Republic of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kuwait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cayman Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KY {
            get {
                return ResourceManager.GetString("KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kazakhstan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lao People&apos;s Democratic Republic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LA {
            get {
                return ResourceManager.GetString("LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lebanon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saint Lucia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liechtenstein과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sri Lanka과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LK {
            get {
                return ResourceManager.GetString("LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liberia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LR {
            get {
                return ResourceManager.GetString("LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lesotho과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LS {
            get {
                return ResourceManager.GetString("LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lithuania과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Luxembourg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latvia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Libya과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LY {
            get {
                return ResourceManager.GetString("LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Morocco과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monaco과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moldova, Republic of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Montenegro과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saint Martin (French part)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MF {
            get {
                return ResourceManager.GetString("MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Madagascar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MG {
            get {
                return ResourceManager.GetString("MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marshall Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MH {
            get {
                return ResourceManager.GetString("MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   North Macedonia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mali과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ML {
            get {
                return ResourceManager.GetString("ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Myanmar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mongolia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macao과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Northern Mariana Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MP {
            get {
                return ResourceManager.GetString("MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Martinique과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MQ {
            get {
                return ResourceManager.GetString("MQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mauritania과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Montserrat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Malta과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mauritius과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MU {
            get {
                return ResourceManager.GetString("MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maldives과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Malawi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MW {
            get {
                return ResourceManager.GetString("MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mexico과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Malaysia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MY {
            get {
                return ResourceManager.GetString("MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mozambique과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MZ {
            get {
                return ResourceManager.GetString("MZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Namibia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Caledonia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Niger과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Norfolk Island과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NF {
            get {
                return ResourceManager.GetString("NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nigeria과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nicaragua과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NI {
            get {
                return ResourceManager.GetString("NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Netherlands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Norway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   North Americal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NORTH_AMERICA {
            get {
                return ResourceManager.GetString("NORTH_AMERICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nepal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NP {
            get {
                return ResourceManager.GetString("NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nauru과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NR {
            get {
                return ResourceManager.GetString("NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Niue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NU {
            get {
                return ResourceManager.GetString("NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Zealand과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NZ {
            get {
                return ResourceManager.GetString("NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oceania과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OCEANIA {
            get {
                return ResourceManager.GetString("OCEANIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oman과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panama과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Peru과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   French Polynesia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PF {
            get {
                return ResourceManager.GetString("PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Papua New Guinea과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PG {
            get {
                return ResourceManager.GetString("PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Philippines과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pakistan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PK {
            get {
                return ResourceManager.GetString("PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Poland과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saint Pierre and Miquelon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pitcairn과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PN {
            get {
                return ResourceManager.GetString("PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puerto Rico과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Palestine, State of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PS {
            get {
                return ResourceManager.GetString("PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portugal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Palau과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PW {
            get {
                return ResourceManager.GetString("PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paraguay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Qatar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Réunion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RE {
            get {
                return ResourceManager.GetString("RE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Romania과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serbia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Russian Federation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rwanda과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saudi Arabia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solomon Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seychelles과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sudan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SD {
            get {
                return ResourceManager.GetString("SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sweden과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Singapore과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saint Helena, Ascension and Tristan da Cunha과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SH {
            get {
                return ResourceManager.GetString("SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slovenia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Svalbard and Jan Mayen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SJ {
            get {
                return ResourceManager.GetString("SJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slovakia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sierra Leone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   San Marino과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Senegal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Somalia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   South America과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SOUTH_AMERICA {
            get {
                return ResourceManager.GetString("SOUTH_AMERICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suriname과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   South Sudan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sao Tome and Principe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   El Salvador과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sint Maarten (Dutch part)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SX {
            get {
                return ResourceManager.GetString("SX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syrian Arab Republic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SY {
            get {
                return ResourceManager.GetString("SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eswatini과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SZ {
            get {
                return ResourceManager.GetString("SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turks and Caicos Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TC {
            get {
                return ResourceManager.GetString("TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   French Southern Territories과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TF {
            get {
                return ResourceManager.GetString("TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Togo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thailand과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tajikistan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tokelau과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TK {
            get {
                return ResourceManager.GetString("TK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timor-Leste과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TL {
            get {
                return ResourceManager.GetString("TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkmenistan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tunisia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tonga과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkey과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trinidad and Tobago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tuvalu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Taiwan, Province of China과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TW {
            get {
                return ResourceManager.GetString("TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tanzania, United Republic of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TZ {
            get {
                return ResourceManager.GetString("TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ukraine과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uganda과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UG {
            get {
                return ResourceManager.GetString("UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   United States Minor Outlying Islands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UM {
            get {
                return ResourceManager.GetString("UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   United States of America과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uruguay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UY {
            get {
                return ResourceManager.GetString("UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uzbekistan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holy See과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saint Vincent and the Grenadines과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Venezuela, Bolivarian Republic of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virgin Islands, British과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VG {
            get {
                return ResourceManager.GetString("VG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virgin Islands, U.S.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VI {
            get {
                return ResourceManager.GetString("VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viet Nam과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VN {
            get {
                return ResourceManager.GetString("VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vanuatu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VU {
            get {
                return ResourceManager.GetString("VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wallis and Futuna과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WF {
            get {
                return ResourceManager.GetString("WF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Samoa과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yemen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string YE {
            get {
                return ResourceManager.GetString("YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mayotte과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string YT {
            get {
                return ResourceManager.GetString("YT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   South Africa과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zambia과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZM {
            get {
                return ResourceManager.GetString("ZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zimbabwe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZW {
            get {
                return ResourceManager.GetString("ZW", resourceCulture);
            }
        }
    }
}
